"""
Translates a human's real keyboard/mouse input into the same named-action
vocabulary env/action_space.py's weapon configs already define for the
agent's (gamepad) output side. You play with keyboard + mouse, not a
controller — configs/keyboard_bindings.yaml (generated by
scripts/calibrate_keyboard_bindings.py, never hand-guessed) maps your real
key/button codes onto action names; this module does the runtime
reduction from "whatever's currently held" down to one action per tick.

No weapon-specific knowledge lives here — this only consumes action names
already defined by a loaded weapon config (via the calibrated bindings
file's own action list), per docs/architecture.md's Design Principles.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import evdev
from evdev import ecodes

from env.config_loader import load_config

KEYBOARD_BINDINGS_SCHEMA = "fly-mhw/keyboard_bindings/v1"

# Real play routinely holds movement while attacking (e.g. a forward
# lunge) — when more than one bound key/button is held at once, this
# resolves the ambiguity by picking the first match here. Attack/dodge
# win over movement since they're the more decisive/rarer input.
ACTION_PRIORITY: tuple[str, ...] = (
    "attack_1",
    "attack_2",
    "dodge",
    "move_forward",
    "move_backward",
    "strafe_left",
    "strafe_right",
)


def code_name(code: int) -> str:
    """Symbolic name for an evdev EV_KEY code, for diagnostics only.
    ecodes.KEY/ecodes.BTN can map a code to a tuple of aliases (e.g. 272 ==
    ('BTN_LEFT', 'BTN_MOUSE')) — always pick the first, so this is always
    a plain string, never a tuple, in logs/JSONL output."""
    name = ecodes.KEY.get(code) or ecodes.BTN.get(code) or str(code)
    return name[0] if isinstance(name, tuple) else name


def find_input_devices(name_patterns: Sequence[str]) -> list[evdev.InputDevice]:
    """List every evdev input device whose .name case-insensitively
    contains one of name_patterns (e.g. "keychron", "mouse"). Opens each
    match via evdev.InputDevice(path) — deliberately NEVER calls .grab():
    a non-grabbing open is a passive listener, the kernel fans events out
    to every open reader, so this does not steal input from the desktop
    or the game. Confirmed live 2026-09-18.

    If nothing matches, prints every available device's path/name (same
    "show everything, let a human pick" fallback list_windows.py uses for
    Hyprland windows) and raises SystemExit rather than silently
    returning an empty list.
    """
    matched: list[evdev.InputDevice] = []
    all_devices = [evdev.InputDevice(path) for path in evdev.list_devices()]
    for dev in all_devices:
        name_lower = dev.name.lower()
        if any(p.lower() in name_lower for p in name_patterns):
            matched.append(dev)
        else:
            dev.close()

    if not matched:
        print(f"No input device matched any of {list(name_patterns)!r}. Available devices:")
        for dev in all_devices:
            print(f"  {dev.path}: {dev.name!r}")
        raise SystemExit(
            "No matching input device found — pass different --devices patterns "
            "matching one of the names printed above."
        )
    return matched


@dataclass(frozen=True)
class KeyBinding:
    action: str
    key: str  # evdev symbolic name — KEY_* (keyboard) or BTN_* (mouse button)


@dataclass
class KeyboardBindings:
    weapon_config: str
    bindings: tuple[KeyBinding, ...]
    device_name_patterns: tuple[str, ...] = ()

    @classmethod
    def from_config(cls, path: str | Path) -> "KeyboardBindings":
        data = load_config(path, KEYBOARD_BINDINGS_SCHEMA)
        bindings = tuple(
            KeyBinding(action=b["action"], key=b["key"]) for b in data["bindings"]
        )
        return cls(
            weapon_config=data["weapon_config"],
            bindings=bindings,
            device_name_patterns=tuple(data.get("device_name_patterns", ())),
        )

    def actions(self) -> list[str]:
        return [b.action for b in self.bindings]

    def code_for(self, action: str) -> int:
        for b in self.bindings:
            if b.action == action:
                return ecodes.ecodes[b.key]
        raise KeyError(f"no binding for action {action!r}")

    def _code_to_action(self) -> dict[int, str]:
        return {ecodes.ecodes[b.key]: b.action for b in self.bindings}


@dataclass
class ActionSample:
    action_name: str
    held_key_names: list[str]  # raw diagnostic (every relevant key/button currently held)
    candidate_actions: list[str]  # every action whose binding was held, in priority order
    collided: bool  # True iff more than one candidate was held at once


class KeyboardActionReducer:
    def __init__(self, bindings: KeyboardBindings, devices: Sequence[evdev.InputDevice]):
        self.bindings = bindings
        self.devices = list(devices)
        self._code_to_action = bindings._code_to_action()

    def close(self):
        for dev in self.devices:
            dev.close()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()

    def sample(self, active_codes: Optional[set[int]] = None) -> ActionSample:
        """Reduce whatever's currently held to one action name.

        active_codes: override for offline testing (see
        tests/test_keyboard_bindings.py) — when None (the real/live path),
        queries device.active_keys() directly for each device, which asks
        the kernel for its instantaneous key-state (EVIOCGKEY) rather than
        tracking down/up events ourselves, so a key pressed and released
        between two .sample() calls can't be silently missed.
        """
        if active_codes is None:
            active_codes = set()
            for dev in self.devices:
                active_codes.update(dev.active_keys())

        held_key_names = [
            code_name(c) for c in active_codes if c in self._code_to_action
        ]
        candidates = [
            action
            for action in ACTION_PRIORITY
            if any(
                self._code_to_action.get(c) == action for c in active_codes
            )
        ]

        if not candidates:
            return ActionSample(
                action_name="idle", held_key_names=held_key_names,
                candidate_actions=[], collided=False,
            )
        return ActionSample(
            action_name=candidates[0],
            held_key_names=held_key_names,
            candidate_actions=candidates,
            collided=len(candidates) > 1,
        )
